### ISSUE TITLE
MySQL connection issues on initial test deployment from cookbook

### ISSUE THREAD

**Issue by zonca** [marius311/boinc-server-docker#30]
thanks @marius311 for providing this! I'd like to use it for a BOINC project I'm helping to build.

I just cloned the repository and followed the instructions until `docker-compose up -d`, but I get 404:

```
wget http://127.0.0.1/boincserver
--2018-03-27 18:22:49--  http://127.0.0.1/boincserver
Connecting to 127.0.0.1:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-03-27 18:22:49 ERROR 404: Not Found.
```

I think this is due to the project container having issues connecting to MySQL:

```
Updating project files in data volume...
Waiting for MySQL server to start...
ERROR 1130 (HY000): Host '172.17.0.3' is not allowed to connect to this MySQL server
Creating database...                                                                                                                Traceback (most recent call last):
  File "<string>", line 5, in <module>                                                                                              
  File "/root/boinc/py/Boinc/database.py", line 283, in create_database
    connect(config, nodb=True)                                                                                                        File "/root/boinc/py/Boinc/database.py", line 270, in connect
    passwd=config.__dict__.get('db_passwd', ''))
  File "/root/boinc/py/Boinc/db_base.py", line 498, in do_connect                                                                   
    passwd=passwd, cursorclass=MySQLdb.cursors.DictCursor)                                                                          
  File "/usr/lib/python2.7/dist-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 187, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (1130, "Host '172.17.0.3' is not allowed to connect to this MySQL server")
```

would you have any suggestions?

some other info below:

```
docker ps
CONTAINER ID        IMAGE                                 COMMAND                  CREATED              STATUS              PORTS                NAMES
1fea3c4994c9        boinc/server_apache:latest-b2d        "docker-php-entrypoi…"   54 seconds ago       Up 40 seconds       0.0.0.0:80->80/tcp   boincserverdocker_apache_1
e6197c79adbb        boinc/server_makeproject:latest-b2d   "/bin/sh -c /root/ma…"   54 seconds ago       Up 41 seconds                            boincserverdocker_makeproject_1
19a9101b93ba        boinc/server_mysql:latest             "docker-entrypoint.s…"   About a minute ago   Up 53 seconds       3306/tcp             boincserverdocker_mysql_1
```

### Docker version

```
docker --version
Docker version 18.03.0-ce, build 0520e24
docker-compose --version
docker-compose version 1.20.1, build 5d8c71b
```

### Apache logs

```
docker logs 1fea3c4994c9
/usr/lib/python2.7/dist-packages/supervisor/options.py:296: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
2018-03-27 22:25:37,113 CRIT Supervisor running as root (no user in config file)
2018-03-27 22:25:37,113 WARN Included extra file "/etc/supervisor/conf.d/supervisord.conf" during parsing
2018-03-27 22:25:37,123 INFO RPC interface 'supervisor' initialized
2018-03-27 22:25:37,124 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2018-03-27 22:25:37,124 INFO supervisord started with pid 1
2018-03-27 22:25:38,127 INFO spawned: 'cron' with pid 7
2018-03-27 22:25:38,133 INFO spawned: 'start' with pid 8
2018-03-27 22:25:38,136 INFO spawned: 'rsyslogd' with pid 9
2018-03-27 22:25:38,143 INFO spawned: 'apache2' with pid 10
2018-03-27 22:25:39,301 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-03-27 22:25:39,301 INFO success: start entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-03-27 22:25:39,301 INFO success: rsyslogd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-03-27 22:25:39,301 INFO success: apache2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

**Comment by marius311** [comment]
Glad you found this project :) 

I'm unable to reproduce using exactly the same versions of docker and docker-compose. Can you try a `docker-compose down -v` then `docker-compose up -d`

I suppose https://github.com/docker-library/mysql/issues/275 could be related but its tough to tell the specific issue there.

**Comment by zonca** [comment]
it looks like that solved the issue! :) I had tried before, but without `-v`, maybe that is why it didn't work?
